server:
  port: 8380
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store:
    key-store-password:
capi:
  namespace: local
  public-endpoint: http://localhost:8380/capi/
  #### Kafka is still experimental ####
  kafka:
    enabled: false
    host:
    topic:
    group-instance:
    group-id:
    ssl:
      enabled: false
      keystore:
        location:
        password:
      truststore:
        location:
        password:
  reverse:
    proxy:
      enabled: false
      host: localhost:8380
  #### DO NOT CHANGE, unless you know exactly that you CAPI to follow Redirects. ###
  #### If you want to disable routes from following redirects ####
  disable:
    redirect: true
  #### Websocket Gateway (Editable Property) ####
  websocket:
    enabled: false
    server:
      host: localhost
      port: 8382
  #### gRPC Gateway (Editable Property) ####
  grpc:
    enabled: false
    server:
      host: localhost
      port: 8383
  #### Enable Traces (Editable Property) ####
  traces:
    enabled: false
    endpoint: http://localhost:9411
  #### Consul Integration (Editable Property) ####
  #### If you want CAPI to search consul for available APIs to be deployed, enable this feature. ####
  consul:
    token:
    hosts: http://localhost:8500
    discovery:
      enabled: true
      timer:
        interval: 10000
  #### Certificate Management (Editable property) ####
  #### If you want to enable certificate management, please provide a trust store (JKS). ####
  trust:
    store:
      enabled: false
      path:
      password:
  version: ^project.version^
  name: ^project.name^
  spring:
    version: ^project.description^
  gateway:
    cors:
      management:
        enabled: true
    error:
      listener:
        enabled: false
        context: /capi-error
        port: 8389
      #### All calls in error will be bridged to this endpoint ####
      endpoint: localhost:8380/capi-error
      ssl: false
#### DO NOT CHANGE THESE SPRING AUTOCONFIGURE EXCLUSIONS #####
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  #### We want persistence to be optional, so we disable autoconfiguration for JPA ####
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  profiles:
    active: default
  ### CAPI Banner, keep it, it is beautiful!
  banner:
    location: classpath:capi.txt
  ### Allow bean definition overriding (Do not change) ###
  main:
    allow-bean-definition-overriding: true
camel:
  main:
    name: capi-gateway
    tracing: false
  component:
    metrics:
      enabled: true
  servlet:
    mapping:
      context-path: /capi/*
#### Actuator Metrics Endpoint Configuration (Do not change) ####
management:
  server:
    port: 8381
  security:
    enabled: false
  endpoint:
    camelroutes:
      enabled: true
  endpoints:
    web:
      base-path: /metrics/
      exposure:
        include: 'health,prometheus,routes,capi,openapi,truststore'

#### Time to live for Sticky Sessions feature ####
sticky:
  session:
    time:
      to:
        live: 2
#### OAUTH2 Support to protect the routes. (Editable properties) ####
oauth2:
  cookieName:
  provider:
    enabled: false
    keys:
      - http://localhost:8080/realms/master/protocol/openid-connect/certs
    host: http://localhost:8080
    realm: /realms/master
    clientId:
    clientSecret:

opa:
  enabled: false
  endpoint: http://localhost:8181