name: capi
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 21
    - uses: actions/checkout@v3.5.3
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v21
    - name: Set Release version env variable
      run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn package --file pom.xml
    - name: Docker login
      run: |
          docker login -u surisoft -p ${{ secrets.DOCKER_HUB_PWD }}
    - name: Build Docker image
      run: docker build . --build-arg "CAPI_VERSION=${{ env.RELEASE_VERSION }}" --file Dockerfile --tag surisoft/capi:${{ env.RELEASE_VERSION }}
    - name: Docker Push
      run: docker push surisoft/capi:${{ env.RELEASE_VERSION }}
